name: Update Docker Images and Notify Discord

on:
  workflow_call:
    inputs:
      course_id:
        required: true
        type: string
    secrets:
      discord_role:
        required: true
      docker_user:
        required: true
      docker_password:
        required: true
      discord_webhook_url:
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  docker_workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout calling repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup notifications
        uses: ./.github/actions/setup-notifications

      - name: Get changed files
        run: |
          files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }})
          echo "FILES<<EOF" >> $GITHUB_ENV
          echo "$files" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.docker_user }}
          password: ${{ secrets.docker_password }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Ensure required directories exist
        run: mkdir -p .github/logs

      - name: Run build_dockers.py
        id: run_build_dockers
        continue-on-error: true
        run: |
          STDOUT_LOG="${{ github.workspace }}/.github/logs/docker_stdout.log"
          STDERR_LOG="${{ github.workspace }}/.github/logs/docker_stderr.log"

          python utils/docker_updates/build_dockers.py \
              --files "${{ env.FILES }}" \
              --output-file "${{ github.workspace }}/.github/logs/docker_output.json" \
              --root-dir "${{ github.workspace }}" \
              > "$STDOUT_LOG" 2> "$STDERR_LOG"

      - name: Send course notification
        if: always()
        uses: ./.github/actions/send-course-notification
        with:
          notification-type: docker
          output-type: Docker
          payload-path: ${{ github.workspace }}/.github/logs/docker_output.json
          stdout-log: ${{ github.workspace }}/.github/logs/docker_stdout.log
          stderr-log: ${{ github.workspace }}/.github/logs/docker_stderr.log
          course-id: ${{ inputs.course_id }}
          discord-role: ${{ secrets.discord_role }}
          discord-webhook-url: ${{ secrets.discord_webhook_url }}
